services:
  web_app:
    build:
      context: .
    image: web_app
    container_name: web_app
    ports:
      - "8000:8000"
    command: python /app/web_server/server.py
    restart: always
    mem_limit: 512m
    
